---
Parameters:
  S3BucketName:
    Type: String
    Default: mintic-bucket-680578888516-us-east-1
    Description: S3 bucket containing proyecto.zip
  
  ProjectZipFile:
    Type: String
    Default: proyecto.zip
    Description: Name of the zip file to deploy

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
      Tags:
        - Key: Name
          Value: MinTic EC2 Role

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instance with HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP traffic
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Allow SSH access
      Tags:
        - Key: Name
          Value: MinTic EC2 Security Group

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0f88e80871fd81e91
      InstanceType: t3.micro
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroups:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Actualizar sistema e instalar paquetes necesarios
          yum update -y
          yum install -y httpd unzip aws-cli
          
          # Iniciar y habilitar Apache
          systemctl start httpd
          systemctl enable httpd
          
          # Descargar proyecto.zip desde S3
          echo "Descargando ${ProjectZipFile} desde s3://${S3BucketName}/"
          aws s3 cp s3://${S3BucketName}/${ProjectZipFile} /tmp/${ProjectZipFile}
          
          # Verificar si la descarga fue exitosa
          if [ -f /tmp/${ProjectZipFile} ]; then
            echo "Archivo descargado exitosamente, descomprimiendo..."
            
            # Descomprimir en el directorio web
            unzip -o /tmp/${ProjectZipFile} -d /var/www/html/
            
            # Ajustar permisos
            chown -R apache:apache /var/www/html/
            chmod -R 755 /var/www/html/
            
            # Limpiar archivo temporal
            rm -f /tmp/${ProjectZipFile}
            
            echo "Proyecto desplegado exitosamente"
          else
            # Si falla, mostrar página de error
            cat > /var/www/html/index.html << EOF
          <h1>Error al descargar el proyecto</h1>
          <p>No se pudo descargar <strong>${ProjectZipFile}</strong> desde el bucket <strong>${S3BucketName}</strong></p>
          <p>Verifica que el archivo exista en S3 y que los permisos IAM sean correctos.</p>
          EOF
            echo "Error: No se pudo descargar el archivo desde S3"
          fi
          
          # Reiniciar Apache
          systemctl restart httpd
      Tags:
        - Key: Name
          Value: MinTic EC2 Instance

Outputs:
  InstanceId:
    Description: ID of the EC2 instance
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'
  
  PublicIP:
    Description: Public IP address of the instance
    Value: !GetAtt EC2Instance.PublicIp
  
  PublicDNS:
    Description: Public DNS name of the instance
    Value: !GetAtt EC2Instance.PublicDnsName
  
  WebsiteURL:
    Description: URL to access the deployed project
    Value: !Sub 'http://${EC2Instance.PublicDnsName}'
  
  S3BucketUsed:
    Description: S3 bucket used for deployment
    Value: !Ref S3BucketName